# Generated by Django 4.2.1 on 2024-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
