# Generated by Django 4.2.1 on 2024-10-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='profile_pic',
        ),
    ]
