# Generated by Django 4.2.1 on 2024-10-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
