# Generated by Django 4.2.1 on 2024-08-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_attachments_created_by_authconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authconfig',
            name='organization',
        ),
    ]
