# Generated by Django 4.2.1 on 2024-08-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_attachments_created_by'),
        ('common', '0011_remove_authconfig_organization'),
    ]

    operations = [
    ]
