# Generated by Django 4.2.1 on 2024-08-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_merge_20240810_1246'),
        ('common', '0012_merge_20240810_2346'),
    ]

    operations = [
    ]
