# Generated by Django 4.2.1 on 2024-08-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_merge_20240812_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER'), ('SALES REP', 'SALES REP'), ('SALES MANAGER', 'SALES MANAGER')], default='USER', max_length=50),
        ),
    ]
