# Generated by Django 4.2.1 on 2024-08-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_profile_role'),
        ('common', '0014_create_default_authconfig'),
    ]

    operations = [
    ]
