# Generated by Django 4.2.1 on 2024-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_merge_20240828_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SALES MANAGER', 'SALES MANAGER'), ('SALES REP', 'SALES REP'), ('USER', 'USER'), ('SALES REP', 'SALES REP'), ('SALES MANAGER', 'SALES MANAGER')], default='USER', max_length=50),
        ),
    ]
