# Generated by Django 4.2.1 on 2024-08-15 11:12

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission


def remove_duplicate_permissions(apps, schema_editor):
    # Connect to the database
    with schema_editor.connection.cursor() as cursor:
        # Find and remove duplicate codenames
        cursor.execute("""
            DELETE FROM auth_permission
            WHERE id IN (
                SELECT id FROM (
                    SELECT MIN(id) as id
                    FROM auth_permission
                    GROUP BY codename
                    HAVING COUNT(*) > 1
                ) AS subquery
            );
        """)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_create_groups"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_permissions),
    ]
