# Generated by Django 4.2.1 on 2024-09-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('common', '0016_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_attachment', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals_comments', to='deals.deal'),
        ),
    ]
