# Generated by Django 4.2.1 on 2024-09-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_attachments_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
