# Generated by Django 4.2.1 on 2024-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SALES MANAGER', 'SALES MANAGER'), ('SALES REP', 'SALES REP'), ('USER', 'USER')], default='USER', max_length=50),
        ),
    ]
