# Generated by Django 4.2.1 on 2024-10-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='real_close_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
