version: '3.8'
services:
  crm-app:
    image: djcrm:1
    container_name: crm-app
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
    depends_on:
      - crm-db
    ports:
      - 8000:8000
    volumes:
      - ../../Django-crm-project:/app
    networks:
      - nw

  crm-db:
    image: postgres:latest
    container_name: crm-db
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/run/postgresql
    networks:
      - nw

networks:
  nw: {}

volumes:
  postgres: