FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG PIP_EXTRA_INDEX_URL

WORKDIR /app

# Install dependencies
COPY requirements.txt /app

RUN apt update && \
    apt install -y git ruby-dev ruby-ffi postgresql-client redis-server wkhtmltopdf && \
    apt clean && \
    gem install sass && \
    gem install compass && \
    apt install nodejs npm -y && \
    npm -g install less && \
    apt install -y python3-pip && \
    python3 -m pip install --no-cache-dir -r requirements.txt && \
    python3 -m pip install --no-cache-dir redis


# Wait for PostgreSQL to be available
RUN apt-get update && apt-get install -y netcat

CMD until nc -z -v -w30 $DBHOST $DBPORT; do \
        echo 'Waiting for PostgreSQL...' && \
        sleep 1; \
    done && \
    python3 manage.py collectstatic --noinput && \
    python3 manage.py migrate && \
    python3 manage.py runserver 0.0.0.0:8000
