# Generated by Django 4.2.1 on 2024-09-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_alter_opportunity_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('ASSIGNED LEAD', 'ASSIGNED LEAD'), ('IN PROCESS', 'IN PROCESS'), ('OPPORTUNITY', 'OPPORTUNITY'), ('QUALIFICATION', 'QUALIFICATION'), ('NEGOTIATION', 'NEGOTIATION'), ('CLOSED WON', 'CLOSED WON'), ('CLOSED LOST', 'CLOSED LOST')], max_length=64, verbose_name='Stage'),
        ),
    ]
